# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170317_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailid',
        ),
    ]
