# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170317_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailid',
            new_name='email',
        ),
    ]
