# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170317_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email id'),
        ),
    ]
